version: '3.4'

services:
  tf-server:
    container_name: tf-server
    image: mmoorman/tf-server:0.1
    network_mode: host
    expose:
     - "8850"
    environment:
     - TF_SERVER_HOST=0.0.0.0
     - TF_SERVER_PORT=8850
    restart: unless-stopped

  canvas-http:
    container_name: canvas-server
    image: fnichol/uhttpd
    network_mode: host
    expose:
     - "80"
    volumes:
     - ./canvas:/www
    restart: unless-stopped